---
elasticsearch:
  hosts:
    Ubuntu1:
      ansible_host: 127.0.0.l
      ansible_port: 22
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_password: vagrant
kibana:
  hosts:
    Ubuntu1:
      ansible_host: 10.0.2.15
      ansible_connection: ssh
      ansible_user: vagrant 
